baseurl = "https://tmachemedze.netlify.com/"
languageCode = "en-us"
title = "Data stories"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = "takwanisamachemedze"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

author = "Takwanisa Machemedze"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  brand = "Takwanisa"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  
[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "Takwanisa"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"
  #tumblr = "*"

  # SNS photo/video sharing
  #instagram = "*"
  #flickr = "*"
  #photo500px = "*"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  #linkedin = "*"
  #xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "tmachemedze"
  #gitlab = "*"
  #bitbucket = "*"
  #stackoverflow = "*"
  #serverfault = "*"

  # Gaming
  #steam = "*"
  #mobygames = "*"

  # Music
  #lastfm = "*"
  #discogs = "*"

  # Other
  #keybase = "*"
